[build]
builder = "NIXPACKS"
watchPatterns = ["src/**", "public/**"]
buildCommand = "npm run build"

[deploy]
numReplicas = 1
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[serve]
port = 3000